theme: jekyll-theme-cayman
title: Systems COR
description: The Systems CoR is a group of researchers at MIT focused on building and investigating large-scale software systems that power modern computers, phones, data centers, and networks, including operating systems, the Internet, wireless networks, databases, and other software infrastructure.
